# Site settings
baseurl = "http://mtldo.com/"
languageCode = "en-us"
title = "Manny Toledo"
author = "Manny Toledo"
theme = "after-dark"
contentdir = "content"
publishdir = "public"
builddrafts = false
canonifyurls = true
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."

[[menu.main]]
  name = "Home"
  weight = 1
  identifier = "home"
  url = "/"
# [[menu.main]]
#   name = "Posts"
#   weight = 2
#   identifier = "post"
#   url = "/post/"

[params]
images = [
  "static/images/server.jpg" # Default Open Graph image for site
]
